apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      serviceAccountName: eks-user
      containers:
        - name: eks-app
          image: exilemirror/react-eks:16
          ports:
            - containerPort: 80
